# Uncloud deployment configuration
# Deploy with: uncloud deploy
#
# Architecture:
# - coordinator: Single instance, serves web UI, manages workers
# - worker: Multiple instances across cluster, connect to coordinator

services:
  # Coordinator - serves the web UI and orchestrates workers
  coordinator:
    image: ghcr.io/justy/fractalzoomer:latest
    x-ports:
      - fractalzoomer.justy.me:8080/https
    environment:
      - MODE=coordinator
      - RUST_LOG=info
      - PORT=8080

  # Workers - one per machine, connect to coordinator
  worker-box1:
    image: ghcr.io/justy/fractalzoomer:latest
    deploy:
      x-machines:
        - box1
    environment:
      - MODE=worker
      - COORDINATOR_URL=ws://coordinator:8080/ws/worker
      - RUST_LOG=info

  worker-megaton:
    image: ghcr.io/justy/fractalzoomer:latest
    deploy:
      x-machines:
        - megaton
    environment:
      - MODE=worker
      - COORDINATOR_URL=ws://coordinator:8080/ws/worker
      - RUST_LOG=info

  worker-gigaton:
    image: ghcr.io/justy/fractalzoomer:latest
    deploy:
      x-machines:
        - gigaton
    environment:
      - MODE=worker
      - COORDINATOR_URL=ws://coordinator:8080/ws/worker
      - RUST_LOG=info

  worker-m1:
    image: ghcr.io/justy/fractalzoomer:latest
    deploy:
      x-machines:
        - m1
    environment:
      - MODE=worker
      - COORDINATOR_URL=ws://coordinator:8080/ws/worker
      - RUST_LOG=info
